# Generated by Django 5.2.8 on 2025-11-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage='containertrack_api.storage_backend.SupabaseStorage', upload_to='')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.container')),
            ],
        ),
    ]
